#!/bin/bash
# Copyright 2022-2023 PUFsecurity
#
# It is licensed under the BSD 3-Clause license; you may not use this file
# except in compliance with the License.
#
# You may obtain a copy of the License at:
#  https://opensource.org/licenses/BSD-3-Clause
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



source ~/.bashrc
BASE=$(dirname "${BASH_SOURCE[0]}")
certs="${BASE}/certs"
device_id_path="$certs/uid.txt"
PROJECT="a-plus-project"
REGION="asia-east1"
KEY_TYPE="es256-pem"
MQTT_PATH="${BASE}/../bin/iot_core_mqtt_client_puf/bin/"
MQTT="./iot_core_mqtt_client_puf"

if [ $# -eq 0 ]; then
    echo "./puf-device-mqtt config-file"
    exit 1
fi
if [ ! -f "$1" ]; then
    echo "$1 env_config no such."
    exit 1
fi

config=$1
registry=$(grep -o '"registry":"[^"]*' "$config" | grep -o '[^"]*$')
device_id=$(cat "$device_id_path") 

echo "Project = $PROJECT"
echo "REGION = $REGION"
echo "Registry = $registry"
echo "Device ID = $device_id"

if [ ! -f "$MQTT_PATH/$MQTT" ]; then
    echo "$MQTT/$MQTT no such."
    exit 1
fi
cd $MQTT_PATH
$MQTT -p $PROJECT -d projects/$PROJECT/locations/$REGION/registries/$registry/devices/$device_id -t /devices/$device_id/events
